version: '3'
services:
  postgres:
    image: "postgres:9.6.12"
    environment:
      POSTGRES_DB: powergrid
      POSTGRES_USER: powergrid
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
